version: 2
jobs:
  build-and-test:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: dotnet tool install -g dotnet-xunit-to-junit
      - run: dotnet tool install -g Cake.Tool
      - run: dotnet cake build.cake 
      - run: dotnet xunit-to-junit ./build/LightStep.Tests.dll.xml ./build/LightStep.Tests.dll.junit.xml
      - store_test_results:
          path: build/LightStep.Tests.dll.junit.xml
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: msbuild /t:Restore
      - run: msbuild src/LightStep/LightStep.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=tracerSign.snk /t:Build
  test:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: msbuild /t:Restore
      - run: msbuild src/LightStep/LightStep.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=tracerSign.snk /t:Build
      - run: msbuild test/LightStep.Tests/LightStep.Tests.csproj /t:Build
      - run: msbuild test/LightStep.Tests/LightStep.Tests.csproj /t:Test
  pack:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: msbuild /t:Restore
      - run: msbuild src/LightStep/LightStep.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=tracerSign.snk /t:Build
      - run: sn -R src/LightStep/bin/Debug/net45/LightStep.dll src/LightStep/tracerSign.snk && sn -vf src/LightStep/bin/Debug/net45/LightStep.dll
      - run: msbuild src/LightStep/LightStep.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=tracerSign.snk /t:Pack /p:PackageOutputPath="/pkg"
      - store_artifacts:
          path: /pkg

  publish:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: msbuild /t:Restore
      - run: msbuild /t:Build
      - run: msbuild src/LightStep/LightStep.csproj /t:Pack
      - run: dotnet nuget push src/LightStep/bin/Debug/*.nupkg -k $NuGet

workflows:
  version: 2
  build-test-and-pack:
    jobs:
      - build
      - test:
          requires:
            - build
      - pack:
          requires:
            - test
          filters:
            branches:
              only: master
